# Generated by Django 4.2.4 on 2023-11-24 04:46

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('shop', '0002_alter_category_options_alter_goods_options_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='goods',
            options={'ordering': ['create_at'], 'verbose_name': 'Товари', 'verbose_name_plural': 'Товари'},
        ),
        migrations.AlterModelOptions(
            name='profile',
            options={'verbose_name': 'Профілі', 'verbose_name_plural': 'Профілі'},
        ),
        migrations.AddField(
            model_name='profile',
            name='username',
            field=models.CharField(max_length=50, null=True, verbose_name="Ім'я користувача"),
        ),
        migrations.AlterField(
            model_name='goods',
            name='category',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='post', to='shop.category', verbose_name='Категорії'),
        ),
        migrations.AlterField(
            model_name='goods',
            name='is_published',
            field=models.BooleanField(default=True, verbose_name='Опубліковано'),
        ),
        migrations.AlterField(
            model_name='profile',
            name='address',
            field=models.CharField(max_length=100, verbose_name='Адреса'),
        ),
        migrations.AlterField(
            model_name='profile',
            name='name_of_shop',
            field=models.CharField(max_length=100, verbose_name='Назва магазину'),
        ),
        migrations.AlterField(
            model_name='profile',
            name='user',
            field=models.OneToOneField(null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='Номер користувача'),
        ),
    ]
